### ISSUE TITLE
Prepend LICENSE to individual files

### ISSUE THREAD

**Issue by sephalon** [pengutronix/usbsdmux#18]
I suggest to prepend the content of the LICENSE file to the individual files, as this would allow tooling to automatically detect the right license.

Ideally, we would also add an [SPDX license identifier](https://spdx.org/ids) to each file header.

**Comment by SmithChart** [comment]
@sephalon please have a look at https://github.com/pengutronix/usbsdmux/pull/21 . Noting license-information like this would be ok for me. Does this fit your needs?

**Comment by sephalon** [comment]
Thanks, LGTM!
